In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/plane-price-prediction/Plane Price.csv

In [2]:
df = pd.read_csv('/kaggle/input/plane-price-prediction/Plane Price.csv')
df.head(3)

,Model Name,Engine Type,HP or lbs thr ea engine,Max speed Knots,Rcmnd cruise Knots,Stall Knots dirty,Fuel gal/lbs,All eng rate of climb,Eng out rate of climb,Takeoff over 50ft,Landing over 50ft,Empty weight lbs,Length ft/in,Wing span ft/in,Range N.M.,Price
0,100 Darter (S.L. Industries),Piston,145,104,91.0,46.0,36,450,900.0,1300.0,"2,050","1,180",25/3,37/5,370,1300000.0
1,7 CCM Champ,Piston,85,89,83.0,44.0,15,600,720.0,800.0,"1,350",820,20/7,36/1,190,1230000.0
2,100 Darter (S.L. Industries),Piston,90,90,78.0,37.0,19,650,475.0,850.0,"1,300",810,21/5,35/0,210,1600000.0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Model Name               517 non-null    object
 1   Engine Type              517 non-null    object
 2   HP or lbs thr ea engine  517 non-null    object
 3   Max speed Knots          497 non-null    object
 4   Rcmnd cruise Knots       507 non-null    float64
 5   Stall Knots dirty        502 non-null    float64
 6   Fuel gal/lbs             517 non-null    int64
 7   All eng rate of climb    513 non-null    object
 8   Eng out rate of climb    491 non-null    float64
 9   Takeoff over 50ft        492 non-null    float64
 10  Landing over 50ft        517 non-null    object
 11  Empty weight lbs         516 non-null    object
 12  Length ft/in             517 non-null    object
 13  Wing span ft/in          517 non-null    object
 14  Range N.M.               499 non-null    object
 15  Price                    507 non-null    float64
dtypes: float64(5), int64(1), object(10)
memory usage: 64.8+ KB

In [4]:
# Virgülleri kaldırıp sayıya çeviren fonksiyon
def clean_and_convert(column):
    # Virgülleri temizle ve sayıya çevir, hata verenleri (string olanları) NaN yap
    return pd.to_numeric(df[column].astype(str).str.replace(',', ''), errors='coerce')

cols_to_fix = ['Max speed Knots', 'HP or lbs thr ea engine', 'All eng rate of climb', 
               'Landing over 50ft', 'Empty weight lbs', 'Range N.M.']

for col in cols_to_fix:
    df[col] = clean_and_convert(col)

In [5]:
df.head(3)

,Model Name,Engine Type,HP or lbs thr ea engine,Max speed Knots,Rcmnd cruise Knots,Stall Knots dirty,Fuel gal/lbs,All eng rate of climb,Eng out rate of climb,Takeoff over 50ft,Landing over 50ft,Empty weight lbs,Length ft/in,Wing span ft/in,Range N.M.,Price
0,100 Darter (S.L. Industries),Piston,145.0,104.0,91.0,46.0,36,450.0,900.0,1300.0,2050.0,1180.0,25/3,37/5,370.0,1300000.0
1,7 CCM Champ,Piston,85.0,89.0,83.0,44.0,15,600.0,720.0,800.0,1350.0,820.0,20/7,36/1,190.0,1230000.0
2,100 Darter (S.L. Industries),Piston,90.0,90.0,78.0,37.0,19,650.0,475.0,850.0,1300.0,810.0,21/5,35/0,210.0,1600000.0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Model Name               517 non-null    object
 1   Engine Type              517 non-null    object
 2   HP or lbs thr ea engine  515 non-null    float64
 3   Max speed Knots          488 non-null    float64
 4   Rcmnd cruise Knots       507 non-null    float64
 5   Stall Knots dirty        502 non-null    float64
 6   Fuel gal/lbs             517 non-null    int64
 7   All eng rate of climb    510 non-null    float64
 8   Eng out rate of climb    491 non-null    float64
 9   Takeoff over 50ft        492 non-null    float64
 10  Landing over 50ft        516 non-null    float64
 11  Empty weight lbs         516 non-null    float64
 12  Length ft/in             517 non-null    object
 13  Wing span ft/in          517 non-null    object
 14  Range N.M.               499 non-null    float64
 15  Price                    507 non-null    float64
dtypes: float64(11), int64(1), object(4)
memory usage: 64.8+ KB

In [7]:
df = pd.get_dummies(df , columns = ['Engine Type'], drop_first = True , dtype = int)

In [8]:
df = df.drop(columns=['Model Name','Length ft/in' , 'Wing span ft/in'] , axis =1)

In [9]:
df.head(3)
df = df.dropna()

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 415 entries, 0 to 516
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   HP or lbs thr ea engine  415 non-null    float64
 1   Max speed Knots          415 non-null    float64
 2   Rcmnd cruise Knots       415 non-null    float64
 3   Stall Knots dirty        415 non-null    float64
 4   Fuel gal/lbs             415 non-null    int64
 5   All eng rate of climb    415 non-null    float64
 6   Eng out rate of climb    415 non-null    float64
 7   Takeoff over 50ft        415 non-null    float64
 8   Landing over 50ft        415 non-null    float64
 9   Empty weight lbs         415 non-null    float64
 10  Range N.M.               415 non-null    float64
 11  Price                    415 non-null    float64
 12  Engine Type_Piston       415 non-null    int64
 13  Engine Type_Propjet      415 non-null    int64
 14  Engine Type_piston       415 non-null    int64
dtypes: float64(11), int64(4)
memory usage: 51.9 KB

In [11]:
y = df['Price']
x = df.drop(columns = ['Price'])

In [12]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x ,y ,test_size = 0.3 , random_state = 22)

In [13]:
# Y için normalizasyon yapılmaz

# outlier etkisini azaltır

# model performansız artar

In [14]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler

In [15]:
ss=StandardScaler()
x_train_ss=ss.fit_transform(x_train)
x_test_ss = ss.transform(x_test)

In [16]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor()

In [17]:
model = rf.fit(x_train , y_train)
model.score(x_test,y_test)

0.9404195466992142

In [18]:
df.sample()

,HP or lbs thr ea engine,Max speed Knots,Rcmnd cruise Knots,Stall Knots dirty,Fuel gal/lbs,All eng rate of climb,Eng out rate of climb,Takeoff over 50ft,Landing over 50ft,Empty weight lbs,Range N.M.,Price,Engine Type_Piston,Engine Type_Propjet,Engine Type_piston
16,450.0,128.0,91.0,58.0,46,990.0,1145.0,750.0,4500.0,2870.0,190.0,1400000.0,1,0,0