In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/audi-a1-listings/Audi_A1_listings.csv

In [2]:
df = pd.read_csv('/kaggle/input/audi-a1-listings/Audi_A1_listings.csv')
df.head(3)

,index,Year,Type,Mileage(miles),Engine,PS,Transmission,Fuel,Number_of_Owners,Price(£),href,PPY,MileageRank,PriceRank,PPYRank,Score
0,0,2018.0,Hatchback,44000.0,1.6L,114.398422,Manual,Diesel,1,14995.0,https://www.autotrader.co.uk/car-details/20221...,2499.166667,215,163,340,718
1,4,2016.0,Hatchback,42596.0,1.0L,93.688363,Manual,Petrol,3,10755.0,https://www.autotrader.co.uk/car-details/20221...,2688.750000,222,330,276,828
2,7,2015.0,Hatchback,42700.0,1.4L,123.274162,Manual,Petrol,2,10799.0,https://www.autotrader.co.uk/car-details/20221...,3599.666667,221,327,94,642

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 471 entries, 0 to 470
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   index             471 non-null    int64
 1   Year              471 non-null    float64
 2   Type              471 non-null    object
 3   Mileage(miles)    471 non-null    float64
 4   Engine            471 non-null    object
 5   PS                471 non-null    float64
 6   Transmission      471 non-null    object
 7   Fuel              471 non-null    object
 8   Number_of_Owners  471 non-null    int64
 9   Price(£)          471 non-null    float64
 10  href              471 non-null    object
 11  PPY               471 non-null    float64
 12  MileageRank       471 non-null    int64
 13  PriceRank         471 non-null    int64
 14  PPYRank           471 non-null    int64
 15  Score             471 non-null    int64
dtypes: float64(5), int64(6), object(5)
memory usage: 59.0+ KB

In [4]:
df = df.drop(columns = ['index','href','MileageRank','PriceRank','PPYRank','Score'])

In [5]:
df.head(3)

,Year,Type,Mileage(miles),Engine,PS,Transmission,Fuel,Number_of_Owners,Price(£),PPY
0,2018.0,Hatchback,44000.0,1.6L,114.398422,Manual,Diesel,1,14995.0,2499.166667
1,2016.0,Hatchback,42596.0,1.0L,93.688363,Manual,Petrol,3,10755.0,2688.750000
2,2015.0,Hatchback,42700.0,1.4L,123.274162,Manual,Petrol,2,10799.0,3599.666667

In [6]:
df.columns = ['yil','kasa','mil','motor','ps','vites','yakit','sahip','fiyat','ppy']

In [7]:
df.head(3)

,yil,kasa,mil,motor,ps,vites,yakit,sahip,fiyat,ppy
0,2018.0,Hatchback,44000.0,1.6L,114.398422,Manual,Diesel,1,14995.0,2499.166667
1,2016.0,Hatchback,42596.0,1.0L,93.688363,Manual,Petrol,3,10755.0,2688.750000
2,2015.0,Hatchback,42700.0,1.4L,123.274162,Manual,Petrol,2,10799.0,3599.666667

In [8]:
df['motor'] = df['motor'].str.replace("L","")
df['motor'] = pd.to_numeric(df['motor'])

In [9]:
df.head(3)

,yil,kasa,mil,motor,ps,vites,yakit,sahip,fiyat,ppy
0,2018.0,Hatchback,44000.0,1.6,114.398422,Manual,Diesel,1,14995.0,2499.166667
1,2016.0,Hatchback,42596.0,1.0,93.688363,Manual,Petrol,3,10755.0,2688.750000
2,2015.0,Hatchback,42700.0,1.4,123.274162,Manual,Petrol,2,10799.0,3599.666667

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 471 entries, 0 to 470
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   yil     471 non-null    float64
 1   kasa    471 non-null    object
 2   mil     471 non-null    float64
 3   motor   471 non-null    float64
 4   ps      471 non-null    float64
 5   vites   471 non-null    object
 6   yakit   471 non-null    object
 7   sahip   471 non-null    int64
 8   fiyat   471 non-null    float64
 9   ppy     471 non-null    float64
dtypes: float64(6), int64(1), object(3)
memory usage: 36.9+ KB

In [11]:
df = pd.get_dummies(df , columns = ['kasa','vites','yakit'] , drop_first = True , dtype = int)

In [12]:
df.head(3)

,yil,mil,motor,ps,sahip,fiyat,ppy,vites_Manual,yakit_Petrol
0,2018.0,44000.0,1.6,114.398422,1,14995.0,2499.166667,1,0
1,2016.0,42596.0,1.0,93.688363,3,10755.0,2688.750000,1,1
2,2015.0,42700.0,1.4,123.274162,2,10799.0,3599.666667,1,1

In [13]:
y = df['fiyat']
x = df.drop(columns = ['fiyat'] , axis=1)

In [14]:
from sklearn.linear_model import LinearRegression
lm = LinearRegression()
model = lm.fit(x,y)

In [15]:
model.predict([[2019,43000,1.6,94.152648,2,2784.246152,0,1]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([17163.64553225])

In [16]:
model.predict([[2017,30000,1.6,95,1,2600,0,1]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([12568.45736165])

In [17]:
model.score(x,y)

0.9595295772839731