In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/student-depression-and-lifestyle-100k-data/student_lifestyle_100k.csv

In [2]:
df = pd.read_csv('/kaggle/input/student-depression-and-lifestyle-100k-data/student_lifestyle_100k.csv')
df.head(3)

,Student_ID,Age,Gender,Department,CGPA,Sleep_Duration,Study_Hours,Social_Media_Hours,Physical_Activity,Stress_Level,Depression
0,1001,22,Female,Science,3.50,7.3,3.3,3.4,114,5,False
1,1002,20,Male,Engineering,2.72,5.5,7.2,6.0,142,2,False
2,1003,20,Male,Medical,3.01,5.4,2.3,1.8,137,3,False

In [3]:
df = df.drop(columns = ['Student_ID'] , axis = 1)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 10 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Age                 100000 non-null  int64
 1   Gender              100000 non-null  object
 2   Department          100000 non-null  object
 3   CGPA                100000 non-null  float64
 4   Sleep_Duration      100000 non-null  float64
 5   Study_Hours         100000 non-null  float64
 6   Social_Media_Hours  100000 non-null  float64
 7   Physical_Activity   100000 non-null  int64
 8   Stress_Level        100000 non-null  int64
 9   Depression          100000 non-null  bool
dtypes: bool(1), float64(4), int64(3), object(2)
memory usage: 7.0+ MB

In [4]:
df = pd.get_dummies(df , columns = ['Gender','Department'], drop_first = True , dtype = int)
df.head(3)

,Age,CGPA,Sleep_Duration,Study_Hours,Social_Media_Hours,Physical_Activity,Stress_Level,Depression,Gender_Male,Department_Business,Department_Engineering,Department_Medical,Department_Science
0,22,3.50,7.3,3.3,3.4,114,5,False,0,0,0,0,1
1,20,2.72,5.5,7.2,6.0,142,2,False,1,0,1,0,0
2,20,3.01,5.4,2.3,1.8,137,3,False,1,0,0,1,0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 13 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Age                     100000 non-null  int64
 1   CGPA                    100000 non-null  float64
 2   Sleep_Duration          100000 non-null  float64
 3   Study_Hours             100000 non-null  float64
 4   Social_Media_Hours      100000 non-null  float64
 5   Physical_Activity       100000 non-null  int64
 6   Stress_Level            100000 non-null  int64
 7   Depression              100000 non-null  bool
 8   Gender_Male             100000 non-null  int64
 9   Department_Business     100000 non-null  int64
 10  Department_Engineering  100000 non-null  int64
 11  Department_Medical      100000 non-null  int64
 12  Department_Science      100000 non-null  int64
dtypes: bool(1), float64(4), int64(8)
memory usage: 9.3 MB

In [6]:
y = df['Depression']
x = df.drop(columns = ['Depression'] , axis = 1)

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [8]:
x_train , x_test , y_train , y_test = train_test_split(x,y, train_size = 0.9 , random_state = 42)

In [9]:
rf = RandomForestClassifier()
model = rf.fit(x_train , y_train)
model.score(x_test , y_test)

0.9003

In [10]:
df['Depression'].value_counts()

Depression
False    89938
True     10062
Name: count, dtype: int64

In [11]:
sonuc = model.predict(x_test)
dfs = pd.DataFrame()
dfs['sonuc'] = sonuc
dfs['gercek'] = y_test.values
dfs['sonuc'].value_counts()

sonuc
False    9950
True       50
Name: count, dtype: int64

In [12]:
dfs['gercek'].value_counts()

gercek
False    9009
True      991
Name: count, dtype: int64

In [13]:
dfs

      sonuc  gercek
0     False   False
1     False   False
2     False   False
3     False   False
4     False   False
...     ...     ...
9995  False   False
9996  False   False
9997  False   False
9998  False    True
9999  False   False

[10000 rows x 2 columns]

In [14]:
dfs['truebil']=(dfs['gercek']==True) & (dfs['sonuc']==True)

In [15]:
dfs['truebil'].value_counts()

truebil
False    9978
True       22
Name: count, dtype: int64

In [16]:
from sklearn.metrics import precision_score,recall_score,f1_score

In [17]:
precision=precision_score(dfs['gercek'],dfs['sonuc'])

In [18]:
recall=recall_score(dfs['gercek'],dfs['sonuc'])

In [19]:
2*(precision*recall)/(precision+recall)

0.04226705091258406

In [20]:
f1_score(dfs['gercek'],dfs['sonuc'])

0.04226705091258405