In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/car-price-turkiye-fiat-egea-2-el-fiyatlar/fiategea.csv

In [2]:
df = pd.read_csv('/kaggle/input/car-price-turkiye-fiat-egea-2-el-fiyatlar/fiategea.csv')
df.head(3)

,marka,model,motorhacmi,motortipi,paket,yil,km,renk,fiyat,sehir
0,Fiat,Egea,1.4,Fire,Urban,2021,101850.00,Beyaz,858000.0,İzmir
1,Fiat,Egea,1.3,Multijet,Easy,2021,195700.00,Beyaz,679000.0,Gaziantep
2,Fiat,Egea,1.6,Multijet,Urban,2025,5820.97,Beyaz,1188250.0,Mersin

In [3]:
df = df.drop(columns = ['marka' , 'model' , 'sehir' , 'renk'])
df.head(3)

   motorhacmi motortipi  paket   yil         km      fiyat
0         1.4      Fire  Urban  2021  101850.00   858000.0
1         1.3  Multijet   Easy  2021  195700.00   679000.0
2         1.6  Multijet  Urban  2025    5820.97  1188250.0

In [4]:
df = pd.get_dummies(df , columns = ['motortipi' , 'paket'] , drop_first = True , dtype = int)
df.head(3)

,motorhacmi,yil,km,fiyat,motortipi_Fire,motortipi_Multijet,motortipi_T4,paket_Easy,paket_Lounge,paket_Mirror,paket_Street,paket_Urban
0,1.4,2021,101850.00,858000.0,1,0,0,0,0,0,0,1
1,1.3,2021,195700.00,679000.0,0,1,0,1,0,0,0,0
2,1.6,2025,5820.97,1188250.0,0,1,0,0,0,0,0,1

In [5]:
y = df['fiyat']
x = df.drop(columns = ['fiyat'] , axis =1)
x.head(3)

,motorhacmi,yil,km,motortipi_Fire,motortipi_Multijet,motortipi_T4,paket_Easy,paket_Lounge,paket_Mirror,paket_Street,paket_Urban
0,1.4,2021,101850.00,1,0,0,0,0,0,0,1
1,1.3,2021,195700.00,0,1,0,1,0,0,0,0
2,1.6,2025,5820.97,0,1,0,0,0,0,0,1

In [6]:
y.head(3)

0     858000.0
1     679000.0
2    1188250.0
Name: fiyat, dtype: float64

In [7]:
from sklearn.model_selection import train_test_split
x_train , x_test ,y_train , y_test = train_test_split(x,y,test_size = 0.33 , random_state = 42)

In [8]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(x_train, y_train)
y_pred = model.predict(x_test)

In [9]:
model.predict([[1.3,2020,100000,0,1,0,0,0,0,0,1]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

array([792814.86])

In [10]:
from sklearn.metrics import mean_absolute_error
real_mae = mean_absolute_error(y_test, y_pred)

print(f"Sade Model Gerçek Hata (TL): {real_mae:,.2f}")

Sade Model Gerçek Hata (TL): 57,785.60