In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/student-grades-intermediate-dataset/Student_Grades.csv

In [2]:
df = pd.read_csv('/kaggle/input/student-grades-intermediate-dataset/Student_Grades.csv')
df.head(3)

   Hours  Practice  TeamWork  MidTerm  FinalExam  Scores Grade
0    2.5       0.5       0.0        2        2.3      21     C
1    5.1       1.5       0.5        4        4.9      47     B
2    3.2       1.0       0.5        3        2.9      27     C

In [3]:
from keras.models import Sequential
from keras.layers import Dense
import pandas as pd
import numpy as np

2026-01-31 11:06:03.749311: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1769857564.104977      17 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1769857564.209961      17 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1769857565.084937      17 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1769857565.085006      17 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1769857565.085011      17 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1769857565.085015      17 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

In [4]:
y = df['Scores']
x = df.drop(columns = ['Scores','Grade'])

y = y.values.astype('float32')
x = x.values.astype('float32')

In [5]:
model = Sequential()
model.add(Dense(16))
model.add(Dense(32,activation = "relu"))
model.add(Dense(32,activation = "relu"))
model.add(Dense(1))

model.compile(optimizer ="adam", loss = "mse")
model.fit(x,y,epochs =128 , batch_size =16)

Epoch 1/128

2026-01-31 11:06:27.519928: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)

2/2 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - loss: 3323.5317
Epoch 2/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 3382.4299
Epoch 3/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 3445.2476
Epoch 4/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 3340.3010
Epoch 5/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 3036.9822
Epoch 6/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 3001.1995
Epoch 7/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 2888.2437
Epoch 8/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 2929.9485
Epoch 9/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 2873.2268
Epoch 10/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 2920.1763
Epoch 11/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 2894.2107
Epoch 12/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 2891.4651
Epoch 13/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 2862.9558
Epoch 14/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 2845.4001
Epoch 15/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 2576.0518
Epoch 16/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 2769.7383
Epoch 17/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 2538.6316
Epoch 18/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 2545.8630
Epoch 19/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 2477.9343
Epoch 20/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 2524.0571
Epoch 21/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 2446.1094
Epoch 22/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 2181.5312
Epoch 23/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 2221.4788
Epoch 24/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 2070.9031
Epoch 25/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 2141.5159
Epoch 26/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 2129.4102
Epoch 27/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 1969.7722
Epoch 28/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 2027.1627
Epoch 29/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 1834.3817
Epoch 30/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 1829.3899
Epoch 31/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 1767.0009
Epoch 32/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 1505.8912
Epoch 33/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 1321.0190
Epoch 34/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 1428.2745
Epoch 35/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 1235.4104
Epoch 36/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 1198.0358
Epoch 37/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 1128.4922
Epoch 38/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 990.6133
Epoch 39/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 903.5496
Epoch 40/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 722.1621
Epoch 41/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 663.7525
Epoch 42/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 602.9720
Epoch 43/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 522.3413
Epoch 44/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 423.5121
Epoch 45/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 351.7496
Epoch 46/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 286.2202
Epoch 47/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 214.3053
Epoch 48/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 182.2833
Epoch 49/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 121.1502
Epoch 50/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 90.4771
Epoch 51/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 53.1668
Epoch 52/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 33.5789
Epoch 53/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 16.6000
Epoch 54/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 8.6362
Epoch 55/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 5.9574
Epoch 56/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 6.3436
Epoch 57/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 7.7349
Epoch 58/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 11.2911
Epoch 59/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 13.4785
Epoch 60/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 15.7283
Epoch 61/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 16.9800
Epoch 62/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 13.2694
Epoch 63/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 15.1766
Epoch 64/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 13.6052
Epoch 65/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 11.1727
Epoch 66/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 10.2339
Epoch 67/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 8.1437
Epoch 68/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 6.8735
Epoch 69/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 6.8586
Epoch 70/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 6.1923
Epoch 71/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 5.2748
Epoch 72/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 6.1150
Epoch 73/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 6.2245
Epoch 74/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 6.7644
Epoch 75/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 5.9392
Epoch 76/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 6.2028
Epoch 77/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 6.7604
Epoch 78/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 6.9229
Epoch 79/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 5.9563
Epoch 80/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 6.7157
Epoch 81/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 5.6591
Epoch 82/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 6.4812
Epoch 83/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 5.8654
Epoch 84/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 6.4795
Epoch 85/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 5.6566
Epoch 86/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 5.9537
Epoch 87/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 6.1741
Epoch 88/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 4.8796
Epoch 89/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 5.4807
Epoch 90/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 6.2277
Epoch 91/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 4.9329
Epoch 92/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 5.4990
Epoch 93/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 6.0185
Epoch 94/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 6.1622
Epoch 95/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 6.0054
Epoch 96/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 4.8827
Epoch 97/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 6.1825
Epoch 98/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 5.7450
Epoch 99/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 4.7431
Epoch 100/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 5.7166
Epoch 101/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 6.1152
Epoch 102/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 5.4955
Epoch 103/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 5.6307
Epoch 104/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 5.5602
Epoch 105/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 6.0147
Epoch 106/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 5.3761
Epoch 107/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 5.4871
Epoch 108/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 5.5743
Epoch 109/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 5.3993
Epoch 110/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 5.2864
Epoch 111/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 5.8255
Epoch 112/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 6.2202
Epoch 113/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 4.9367
Epoch 114/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 5.6377
Epoch 115/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 5.1652
Epoch 116/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 5.0934
Epoch 117/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 5.6435
Epoch 118/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 5.4448
Epoch 119/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 5.0526
Epoch 120/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 5.3943
Epoch 121/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 5.6187
Epoch 122/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 6.1124
Epoch 123/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 5.6634
Epoch 124/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 5.7728
Epoch 125/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 5.9873
Epoch 126/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 5.5893
Epoch 127/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 6.0341
Epoch 128/128
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 5.6924

In [6]:
df.head(3)

   Hours  Practice  TeamWork  MidTerm  FinalExam  Scores Grade
0    2.5       0.5       0.0        2        2.3      21     C
1    5.1       1.5       0.5        4        4.9      47     B
2    3.2       1.0       0.5        3        2.9      27     C

In [7]:
model.predict(np.array([[3,1,1,2,3.3]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step

array([[27.403706]], dtype=float32)