In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/car-price-turkiye-fiat-egea-2-el-fiyatlar/fiategea.csv

In [2]:
df = pd.read_csv('/kaggle/input/car-price-turkiye-fiat-egea-2-el-fiyatlar/fiategea.csv')
df.head(5)

,marka,model,motorhacmi,motortipi,paket,yil,km,renk,fiyat,sehir
0,Fiat,Egea,1.4,Fire,Urban,2021,101850.00,Beyaz,858000.0,İzmir
1,Fiat,Egea,1.3,Multijet,Easy,2021,195700.00,Beyaz,679000.0,Gaziantep
2,Fiat,Egea,1.6,Multijet,Urban,2025,5820.97,Beyaz,1188250.0,Mersin
3,Fiat,Egea,1.3,Multijet,Easy,2023,17640.00,Beyaz,872030.0,İstanbul
4,Fiat,Egea,1.3,Multijet,Urban,2021,74880.00,Kırmızı,892400.0,Rize

In [3]:
df = df.drop(columns = ['marka' , 'model' , 'sehir'])
df.head(5)

   motorhacmi motortipi  paket   yil         km     renk      fiyat
0         1.4      Fire  Urban  2021  101850.00    Beyaz   858000.0
1         1.3  Multijet   Easy  2021  195700.00    Beyaz   679000.0
2         1.6  Multijet  Urban  2025    5820.97    Beyaz  1188250.0
3         1.3  Multijet   Easy  2023   17640.00    Beyaz   872030.0
4         1.3  Multijet  Urban  2021   74880.00  Kırmızı   892400.0

In [4]:
df = pd.get_dummies(df , columns=['motortipi' , 'paket' , 'renk'], drop_first = True , dtype = int)
df.head(5)

,motorhacmi,yil,km,fiyat,motortipi_Fire,motortipi_Multijet,motortipi_T4,paket_Easy,paket_Lounge,paket_Mirror,...,renk_Kahverengi,renk_Kırmızı,renk_Lacivert,renk_Mavi,renk_Mavi (metalik),renk_Siyah,renk_Turkuaz,renk_Yeşil,renk_Yeşil (metalik),renk_Şampanya
0,1.4,2021,101850.00,858000.0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1.3,2021,195700.00,679000.0,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1.6,2025,5820.97,1188250.0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1.3,2023,17640.00,872030.0,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1.3,2021,74880.00,892400.0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0

In [5]:
df['arac_yasi'] = 2026 - df['yil']
df = df.drop(columns = ['yil'])
df.head(5)

,motorhacmi,km,fiyat,motortipi_Fire,motortipi_Multijet,motortipi_T4,paket_Easy,paket_Lounge,paket_Mirror,paket_Street,...,renk_Kırmızı,renk_Lacivert,renk_Mavi,renk_Mavi (metalik),renk_Siyah,renk_Turkuaz,renk_Yeşil,renk_Yeşil (metalik),renk_Şampanya,arac_yasi
0,1.4,101850.00,858000.0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5
1,1.3,195700.00,679000.0,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,5
2,1.6,5820.97,1188250.0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,1.3,17640.00,872030.0,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,3
4,1.3,74880.00,892400.0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,5

In [6]:
y = df['fiyat'].values
x = df.drop(columns = ['fiyat'] , axis = 1).values
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x, y , test_size=0.33 , random_state=42)

In [7]:
from sklearn.preprocessing import StandardScaler
x_sc = StandardScaler()

x_train = x_sc.fit_transform(x_train)
x_test = x_sc.transform(x_test)

y_sc = StandardScaler()

y_train = y_sc.fit_transform(y_train.reshape(-1,1))
y_test  = y_sc.transform(y_test.reshape(-1,1))

x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
y_train = y_train.astype('float32')
y_test = y_test.astype('float32')

In [8]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam

model = Sequential()

# Katmanları biraz daha genişletelim ki Egea'nın paket/renk/yaş kombinasyonlarını çözebilsin
model.add(Dense(units=64, activation='relu', input_shape=(x_train.shape[1],)))
model.add(Dense(units=32, activation='relu'))
model.add(Dropout(0.2))

# Çıkış katmanı
model.add(Dense(units=1 , activation = 'linear'))
# Learning rate'i doğrudan burada veriyoruz
model.compile(optimizer=Adam(learning_rate=0.001), loss='mse', metrics=['mae'])

model.summary()


# Eğitimi başlatıyoruz
history = model.fit(
    x_train,
    y_train,
    epochs=100,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

2026-01-31 21:52:42.412856: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1769896362.631410      17 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1769896362.697012      17 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1769896363.219827      17 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1769896363.219889      17 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1769896363.219892      17 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1769896363.219894      17 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
2026-01-31 21:52:55.891870: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │         1,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,969 (15.50 KB)

 Trainable params: 3,969 (15.50 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 1.0112 - mae: 0.7780 - val_loss: 0.5343 - val_mae: 0.5665
Epoch 2/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6708 - mae: 0.6057 - val_loss: 0.3595 - val_mae: 0.4572
Epoch 3/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.4045 - mae: 0.4505 - val_loss: 0.2877 - val_mae: 0.4189
Epoch 4/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3983 - mae: 0.4639 - val_loss: 0.2451 - val_mae: 0.3857
Epoch 5/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3834 - mae: 0.4276 - val_loss: 0.2297 - val_mae: 0.3715
Epoch 6/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3620 - mae: 0.4148 - val_loss: 0.2197 - val_mae: 0.3611
Epoch 7/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2616 - mae: 0.3750 - val_loss: 0.2148 - val_mae: 0.3533
Epoch 8/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2644 - mae: 0.3692 - val_loss: 0.2084 - val_mae: 0.3448
Epoch 9/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2759 - mae: 0.3758 - val_loss: 0.2062 - val_mae: 0.3434
Epoch 10/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2297 - mae: 0.3600 - val_loss: 0.2133 - val_mae: 0.3508
Epoch 11/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3301 - mae: 0.3889 - val_loss: 0.2060 - val_mae: 0.3410
Epoch 12/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2580 - mae: 0.3498 - val_loss: 0.2013 - val_mae: 0.3390
Epoch 13/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2326 - mae: 0.3614 - val_loss: 0.1988 - val_mae: 0.3375
Epoch 14/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2801 - mae: 0.3824 - val_loss: 0.2012 - val_mae: 0.3366
Epoch 15/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2125 - mae: 0.3491 - val_loss: 0.1974 - val_mae: 0.3326
Epoch 16/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1964 - mae: 0.3309 - val_loss: 0.2035 - val_mae: 0.3316
Epoch 17/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2328 - mae: 0.3529 - val_loss: 0.1972 - val_mae: 0.3310
Epoch 18/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1673 - mae: 0.2994 - val_loss: 0.1950 - val_mae: 0.3276
Epoch 19/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2107 - mae: 0.3356 - val_loss: 0.1987 - val_mae: 0.3276
Epoch 20/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2421 - mae: 0.3453 - val_loss: 0.1956 - val_mae: 0.3256
Epoch 21/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2393 - mae: 0.3554 - val_loss: 0.2003 - val_mae: 0.3330
Epoch 22/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2196 - mae: 0.3330 - val_loss: 0.1980 - val_mae: 0.3229
Epoch 23/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2057 - mae: 0.3277 - val_loss: 0.1924 - val_mae: 0.3248
Epoch 24/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2129 - mae: 0.3440 - val_loss: 0.1951 - val_mae: 0.3260
Epoch 25/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1925 - mae: 0.3182 - val_loss: 0.1920 - val_mae: 0.3242
Epoch 26/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1900 - mae: 0.3199 - val_loss: 0.1903 - val_mae: 0.3211
Epoch 27/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1871 - mae: 0.3197 - val_loss: 0.1913 - val_mae: 0.3216
Epoch 28/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1678 - mae: 0.3116 - val_loss: 0.1882 - val_mae: 0.3199
Epoch 29/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1737 - mae: 0.3017 - val_loss: 0.1919 - val_mae: 0.3254
Epoch 30/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1770 - mae: 0.3074 - val_loss: 0.1937 - val_mae: 0.3255
Epoch 31/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1691 - mae: 0.2915 - val_loss: 0.1861 - val_mae: 0.3203
Epoch 32/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1695 - mae: 0.3081 - val_loss: 0.1850 - val_mae: 0.3169
Epoch 33/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1748 - mae: 0.3061 - val_loss: 0.1826 - val_mae: 0.3164
Epoch 34/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1798 - mae: 0.3144 - val_loss: 0.1922 - val_mae: 0.3212
Epoch 35/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1574 - mae: 0.2917 - val_loss: 0.1884 - val_mae: 0.3191
Epoch 36/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1747 - mae: 0.3048 - val_loss: 0.1867 - val_mae: 0.3172
Epoch 37/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1761 - mae: 0.2968 - val_loss: 0.1898 - val_mae: 0.3194
Epoch 38/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1615 - mae: 0.2972 - val_loss: 0.1980 - val_mae: 0.3290
Epoch 39/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1608 - mae: 0.3026 - val_loss: 0.1859 - val_mae: 0.3171
Epoch 40/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1724 - mae: 0.3047 - val_loss: 0.1876 - val_mae: 0.3172
Epoch 41/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1759 - mae: 0.3037 - val_loss: 0.1884 - val_mae: 0.3206
Epoch 42/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1532 - mae: 0.2924 - val_loss: 0.1909 - val_mae: 0.3200
Epoch 43/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1542 - mae: 0.2962 - val_loss: 0.1922 - val_mae: 0.3229
Epoch 44/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1555 - mae: 0.2934 - val_loss: 0.1881 - val_mae: 0.3189
Epoch 45/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1944 - mae: 0.3224 - val_loss: 0.1843 - val_mae: 0.3166
Epoch 46/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1883 - mae: 0.3061 - val_loss: 0.1886 - val_mae: 0.3203
Epoch 47/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1877 - mae: 0.3126 - val_loss: 0.1887 - val_mae: 0.3175
Epoch 48/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1875 - mae: 0.3152 - val_loss: 0.1876 - val_mae: 0.3187
Epoch 49/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1905 - mae: 0.3100 - val_loss: 0.1901 - val_mae: 0.3182
Epoch 50/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1536 - mae: 0.2848 - val_loss: 0.1873 - val_mae: 0.3163
Epoch 51/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1725 - mae: 0.2981 - val_loss: 0.1909 - val_mae: 0.3191
Epoch 52/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1496 - mae: 0.2839 - val_loss: 0.1889 - val_mae: 0.3193
Epoch 53/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1788 - mae: 0.3027 - val_loss: 0.1882 - val_mae: 0.3217
Epoch 54/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1557 - mae: 0.2876 - val_loss: 0.1907 - val_mae: 0.3210
Epoch 55/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1710 - mae: 0.2887 - val_loss: 0.1861 - val_mae: 0.3171
Epoch 56/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1547 - mae: 0.2835 - val_loss: 0.1929 - val_mae: 0.3208
Epoch 57/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1750 - mae: 0.3077 - val_loss: 0.1913 - val_mae: 0.3204
Epoch 58/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1461 - mae: 0.2741 - val_loss: 0.1910 - val_mae: 0.3179
Epoch 59/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1490 - mae: 0.2863 - val_loss: 0.1890 - val_mae: 0.3193
Epoch 60/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1892 - mae: 0.3068 - val_loss: 0.1889 - val_mae: 0.3204
Epoch 61/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1620 - mae: 0.2860 - val_loss: 0.1918 - val_mae: 0.3220
Epoch 62/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1702 - mae: 0.2881 - val_loss: 0.1906 - val_mae: 0.3159
Epoch 63/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1670 - mae: 0.3013 - val_loss: 0.1884 - val_mae: 0.3162
Epoch 64/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1514 - mae: 0.2793 - val_loss: 0.1922 - val_mae: 0.3183
Epoch 65/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1508 - mae: 0.2910 - val_loss: 0.1950 - val_mae: 0.3244
Epoch 66/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1922 - mae: 0.3070 - val_loss: 0.1899 - val_mae: 0.3178
Epoch 67/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1479 - mae: 0.2806 - val_loss: 0.1950 - val_mae: 0.3222
Epoch 68/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1332 - mae: 0.2709 - val_loss: 0.1971 - val_mae: 0.3266
Epoch 69/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1926 - mae: 0.3027 - val_loss: 0.1910 - val_mae: 0.3211
Epoch 70/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1611 - mae: 0.2982 - val_loss: 0.1959 - val_mae: 0.3230
Epoch 71/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1528 - mae: 0.2801 - val_loss: 0.1965 - val_mae: 0.3223
Epoch 72/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1669 - mae: 0.3025 - val_loss: 0.1913 - val_mae: 0.3216
Epoch 73/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1846 - mae: 0.3210 - val_loss: 0.1873 - val_mae: 0.3163
Epoch 74/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1688 - mae: 0.2889 - val_loss: 0.1906 - val_mae: 0.3202
Epoch 75/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1444 - mae: 0.2807 - val_loss: 0.1911 - val_mae: 0.3199
Epoch 76/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1505 - mae: 0.2896 - val_loss: 0.1973 - val_mae: 0.3236
Epoch 77/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1433 - mae: 0.2756 - val_loss: 0.1921 - val_mae: 0.3189
Epoch 78/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1415 - mae: 0.2747 - val_loss: 0.1951 - val_mae: 0.3224
Epoch 79/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1499 - mae: 0.2790 - val_loss: 0.1971 - val_mae: 0.3228
Epoch 80/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1612 - mae: 0.2959 - val_loss: 0.1960 - val_mae: 0.3231
Epoch 81/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1594 - mae: 0.2928 - val_loss: 0.2022 - val_mae: 0.3246
Epoch 82/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1627 - mae: 0.2884 - val_loss: 0.1966 - val_mae: 0.3206
Epoch 83/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1426 - mae: 0.2836 - val_loss: 0.1988 - val_mae: 0.3212
Epoch 84/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1559 - mae: 0.2829 - val_loss: 0.2042 - val_mae: 0.3259
Epoch 85/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1312 - mae: 0.2632 - val_loss: 0.2013 - val_mae: 0.3318
Epoch 86/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1271 - mae: 0.2613 - val_loss: 0.2011 - val_mae: 0.3263
Epoch 87/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1317 - mae: 0.2653 - val_loss: 0.2074 - val_mae: 0.3292
Epoch 88/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1703 - mae: 0.2805 - val_loss: 0.1975 - val_mae: 0.3264
Epoch 89/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1875 - mae: 0.3169 - val_loss: 0.2019 - val_mae: 0.3249
Epoch 90/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2170 - mae: 0.3277 - val_loss: 0.2034 - val_mae: 0.3255
Epoch 91/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1586 - mae: 0.2841 - val_loss: 0.2012 - val_mae: 0.3280
Epoch 92/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1791 - mae: 0.3012 - val_loss: 0.2019 - val_mae: 0.3250
Epoch 93/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2014 - mae: 0.3140 - val_loss: 0.2021 - val_mae: 0.3283
Epoch 94/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1531 - mae: 0.2875 - val_loss: 0.1898 - val_mae: 0.3198
Epoch 95/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1664 - mae: 0.2860 - val_loss: 0.1927 - val_mae: 0.3202
Epoch 96/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1347 - mae: 0.2612 - val_loss: 0.1966 - val_mae: 0.3215
Epoch 97/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1363 - mae: 0.2575 - val_loss: 0.1982 - val_mae: 0.3231
Epoch 98/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1555 - mae: 0.2930 - val_loss: 0.2016 - val_mae: 0.3270
Epoch 99/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1380 - mae: 0.2688 - val_loss: 0.1933 - val_mae: 0.3213
Epoch 100/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1309 - mae: 0.2693 - val_loss: 0.1953 - val_mae: 0.3241

In [9]:
# -------------------------------------------------
# 1️⃣2️⃣ TEST DEĞERLENDİRMESİ (SCALE'LI)
# -------------------------------------------------
test_loss, test_mae = model.evaluate(x_test, y_test)
print("Scaled Test MAE:", test_mae)

# -------------------------------------------------
# 1️⃣3️⃣ GERÇEK TL MAE HESABI (🔥 EN ÖNEMLİ 🔥)
# -------------------------------------------------
# GPT'nin hatasını düzelten gerçek TL MAE hesabı:
y_pred_scaled = model.predict(x_test)
y_pred = y_sc.inverse_transform(y_pred_scaled) # Tahminler TL oldu
y_test_real = y_sc.inverse_transform(y_test)   # Gerçek fiyatlar da TL oldu (EKSİK BURASIYDI)

real_mae = np.mean(np.abs(y_pred.flatten() - y_test_real.flatten()))
print("Gerçek MAE (TL):", real_mae)

11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2468 - mae: 0.3625
Scaled Test MAE: 0.358838826417923
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
Gerçek MAE (TL): 55807.777

In [10]:
df.head(5)

,motorhacmi,km,fiyat,motortipi_Fire,motortipi_Multijet,motortipi_T4,paket_Easy,paket_Lounge,paket_Mirror,paket_Street,...,renk_Kırmızı,renk_Lacivert,renk_Mavi,renk_Mavi (metalik),renk_Siyah,renk_Turkuaz,renk_Yeşil,renk_Yeşil (metalik),renk_Şampanya,arac_yasi
0,1.4,101850.00,858000.0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5
1,1.3,195700.00,679000.0,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,5
2,1.6,5820.97,1188250.0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,1.3,17640.00,872030.0,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,3
4,1.3,74880.00,892400.0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,5